#!/usr/bin/env bash
# Generate the C-side exact vGPU identity table from deploy/lib/vgpu-profiles.sh.
set -euo pipefail

here=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
repo_root=$(cd "$here/../../.." && pwd)
# shellcheck source=../../lib/vgpu-profiles.sh
source "$repo_root/deploy/lib/vgpu-profiles.sh"

output="$here/vgpu_profile_catalog.h"
check_only=0
case "${1:-}" in
    '') ;;
    --check) check_only=1 ;;
    *)
        echo "usage: $0 [--check]" >&2
        exit 2
        ;;
esac

vgpu_profile_validate_catalog
catalog_sha256=$(vgpu_profile_catalog_sha256)
[[ "$catalog_sha256" =~ ^[0-9A-F]{64}$ ]] || {
    echo "invalid canonical vGPU profile catalog hash" >&2
    exit 1
}

tmp=$(mktemp "$here/.vgpu-profile-catalog.XXXXXXXX")
trap 'rm -f -- "$tmp"' EXIT

c_string() {
    jq -Rn --arg value "$1" '$value'
}

{
    cat <<'EOF'
/* Generated by generate-profile-catalog.sh.  Do not edit by hand. */
#ifndef QEMU_VGPU_PROFILE_CATALOG_H
#define QEMU_VGPU_PROFILE_CATALOG_H

#include <stddef.h>
#include <stdint.h>

typedef struct {
    const char *key;
    const char *name;
    const char *board_brand;
    const char *board_model;
    const char *memory_type_name;
    const char *memory_maker_name;
    const char *memory_maker_nvapi_name;
    const char *identity_scope;
    const char *vbios_version;
    uint32_t pci_vendor_id;
    uint32_t pci_device_id;
    uint32_t pci_subvendor_id;
    uint32_t pci_subdevice_id;
    uint32_t pci_revision_id;
    uint32_t vram_mb;
    uint32_t core_clock_khz;
    uint32_t boost_clock_khz;
    uint32_t memory_raw_clock_khz;
    uint32_t memory_bus_bits;
    uint32_t memory_bandwidth_mbps;
    uint32_t memory_type;
    uint32_t memory_maker;
    uint32_t cuda_cores;
    uint32_t shader_subpipes;
    uint32_t rop_count;
    uint32_t tmu_count;
    uint32_t architecture;
    uint32_t implementation;
    uint32_t chip_revision;
    uint32_t pcie_width;
    uint32_t ray_tracing_cores;
    uint32_t tensor_cores;
} QemuVgpuProfileContract;

EOF
    printf '#define QEMU_VGPU_PROFILE_CATALOG_SCHEMA %su\n' \
        "$VGPU_PROFILE_CATALOG_SCHEMA"
    printf '#define QEMU_VGPU_PROFILE_CATALOG_SHA256 %s\n\n' \
        "$(c_string "$catalog_sha256")"
    printf 'static const QemuVgpuProfileContract qemu_vgpu_profile_contracts[] = {\n'
    while IFS= read -r profile_key; do
        vgpu_profile_load "$profile_key"
        vgpu_profile_capability_load "$profile_key"
        printf '    { %s, %s, %s, %s, %s, %s, %s, %s, %s,\n' \
            "$(c_string "$GPU_PROFILE")" \
            "$(c_string "$GPU_NAME")" \
            "$(c_string "$GPU_BOARD_BRAND")" \
            "$(c_string "$GPU_BOARD_MODEL")" \
            "$(c_string "$GPU_MEMORY_TYPE")" \
            "$(c_string "$GPU_MEMORY_MAKER")" \
            "$(c_string "$GPU_MEMORY_MAKER_NVAPI_NAME")" \
            "$(c_string "$GPU_IDENTITY_SCOPE")" \
            "$(c_string "${GPU_VBIOS#Version }")"
        printf '      0x%04Xu, 0x%04Xu, 0x%04Xu, 0x%04Xu, 0x%02Xu,\n' \
            "$((GPU_PCI_VID))" "$((GPU_PCI_DID))" \
            "$((GPU_SUB_VID))" "$((GPU_SUB_DID))" "$((GPU_REV))"
        printf '      %uu, %uu, %uu, %uu, %uu, %uu, %uu, %uu,\n' \
            "$GPU_VRAM_MB" "$((GPU_CORE_MHZ * 1000))" \
            "$((GPU_BOOST_MHZ * 1000))" "$((GPU_MEMORY_MHZ * 2000))" \
            "$GPU_MEMORY_BUS_BITS" "$GPU_MEMORY_BANDWIDTH_MBPS" \
            "$GPU_MEMORY_TYPE_NVAPI" "$GPU_MEMORY_MAKER_NVAPI"
        printf '      %uu, %uu, %uu, %uu, 0x%Xu, %uu, 0x%Xu, %uu, %uu, %uu },\n' \
            "$GPU_CUDA_CORES" "$GPU_SHADER_SUBPIPES" \
            "$GPU_ROP_COUNT" "$GPU_TMU_COUNT" "$((GPU_ARCHITECTURE))" \
            "$GPU_IMPLEMENTATION" "$((GPU_CHIP_REVISION))" \
            "$GPU_PCIE_WIDTH" "$GPU_RAY_TRACING_CORES" \
            "$GPU_TENSOR_CORES"
    done < <(vgpu_profile_keys)
    cat <<'EOF'
};

#define QEMU_VGPU_PROFILE_CONTRACT_COUNT \
    (sizeof(qemu_vgpu_profile_contracts) / \
     sizeof(qemu_vgpu_profile_contracts[0]))

#endif
EOF
} >"$tmp"

if ((check_only)); then
    cmp -s -- "$tmp" "$output" || {
        echo "stale generated catalog: $output" >&2
        exit 1
    }
else
    chmod 0644 "$tmp"
    mv -fT -- "$tmp" "$output"
    trap - EXIT
fi
