/* Generated by generate-profile-catalog.sh.  Do not edit by hand. */
#ifndef QEMU_VGPU_PROFILE_CATALOG_H
#define QEMU_VGPU_PROFILE_CATALOG_H

#include <stddef.h>
#include <stdint.h>

typedef struct {
    const char *key;
    const char *name;
    const char *board_brand;
    const char *board_model;
    const char *memory_type_name;
    const char *memory_maker_name;
    const char *memory_maker_nvapi_name;
    const char *identity_scope;
    const char *vbios_version;
    uint32_t pci_vendor_id;
    uint32_t pci_device_id;
    uint32_t pci_subvendor_id;
    uint32_t pci_subdevice_id;
    uint32_t pci_revision_id;
    uint32_t vram_mb;
    uint32_t core_clock_khz;
    uint32_t boost_clock_khz;
    uint32_t memory_raw_clock_khz;
    uint32_t memory_bus_bits;
    uint32_t memory_bandwidth_mbps;
    uint32_t memory_type;
    uint32_t memory_maker;
    uint32_t cuda_cores;
    uint32_t shader_subpipes;
    uint32_t rop_count;
    uint32_t tmu_count;
    uint32_t architecture;
    uint32_t implementation;
    uint32_t chip_revision;
    uint32_t pcie_width;
} QemuVgpuProfileContract;

#define QEMU_VGPU_PROFILE_CATALOG_SCHEMA 2u
#define QEMU_VGPU_PROFILE_CATALOG_SHA256 "DF5077AE641CADFA30E2372E4846A59372B46ADBF222A12E5EE3F6AF1D8C613D"

static const QemuVgpuProfileContract qemu_vgpu_profile_contracts[] = {
    { "gtx750ti_2gb", "NVIDIA GeForce GTX 750 Ti", "NVIDIA", "Reference", "GDDR5", "Samsung", "Samsung", "B:system-pci=host-mdev,catalog=protected-user-mode", "82.07.41.00.32",
      0x10DEu, 0x1380u, 0x10DEu, 0x1380u, 0xA2u,
      2048u, 1020000u, 1085000u, 2700000u, 128u, 86400u, 8u, 1u,
      640u, 5u, 16u, 40u, 0x110u, 7u, 0x12u, 16u },
    { "gt1030_2gb", "NVIDIA GeForce GT 1030", "ASUS", "OEM 85F9", "GDDR5", "Samsung", "Samsung", "B:system-pci=host-mdev,catalog=protected-user-mode", "86.08.46.00.81",
      0x10DEu, 0x1D01u, 0x1043u, 0x85F9u, 0xA1u,
      2048u, 1227000u, 1468000u, 3004000u, 64u, 48100u, 8u, 1u,
      384u, 3u, 16u, 24u, 0x130u, 8u, 0x11u, 4u },
    { "gtx1050_2gb", "NVIDIA GeForce GTX 1050", "Dell", "OEM", "GDDR5", "Samsung", "Samsung", "B:system-pci=host-mdev,catalog=protected-user-mode", "86.07.39.40.F4",
      0x10DEu, 0x1C81u, 0x1028u, 0x11C0u, 0xA1u,
      2048u, 1354000u, 1455000u, 3504000u, 128u, 112000u, 8u, 1u,
      640u, 5u, 32u, 40u, 0x130u, 7u, 0x11u, 16u },
    { "gtx750ti_asus_2gb", "NVIDIA GeForce GTX 750 Ti", "ASUS", "OC", "GDDR5", "Samsung", "Samsung", "B:system-pci=host-mdev,catalog=protected-user-mode", "82.07.32.00.20",
      0x10DEu, 0x1380u, 0x1043u, 0x84BBu, 0xA2u,
      2048u, 1072000u, 1150000u, 2700000u, 128u, 86400u, 8u, 1u,
      640u, 5u, 16u, 40u, 0x110u, 7u, 0x12u, 16u },
    { "gtx750ti_msi_2gb", "NVIDIA GeForce GTX 750 Ti", "MSI", "OC", "GDDR5", "SK hynix", "Hynix", "B:system-pci=host-mdev,catalog=protected-user-mode", "82.07.25.00.1F",
      0x10DEu, 0x1380u, 0x1462u, 0x8A9Bu, 0xA2u,
      2048u, 1059000u, 1137000u, 2700000u, 128u, 86400u, 8u, 6u,
      640u, 5u, 16u, 40u, 0x110u, 7u, 0x12u, 16u },
    { "gtx750ti_gigabyte_2gb", "NVIDIA GeForce GTX 750 Ti", "Gigabyte", "OC", "GDDR5", "Micron", "Micron", "B:system-pci=host-mdev,catalog=protected-user-mode", "82.07.55.00.05",
      0x10DEu, 0x1380u, 0x1458u, 0x362Du, 0xA2u,
      2048u, 1033000u, 1111000u, 2700000u, 128u, 86400u, 8u, 10u,
      640u, 5u, 16u, 40u, 0x110u, 7u, 0x12u, 16u },
    { "gt1030_galax_2gb", "NVIDIA GeForce GT 1030", "GALAX", "EXOC White", "GDDR5", "Samsung", "Samsung", "B:system-pci=host-mdev,catalog=protected-user-mode", "86.08.0C.00.2B",
      0x10DEu, 0x1D01u, 0x10DEu, 0x11C7u, 0xA1u,
      2048u, 1253000u, 1506000u, 3004000u, 64u, 48100u, 8u, 1u,
      384u, 3u, 16u, 24u, 0x130u, 8u, 0x11u, 4u },
    { "gt1030_asus_2gb", "NVIDIA GeForce GT 1030", "ASUS", "Silent", "GDDR5", "SK hynix", "Hynix", "B:system-pci=host-mdev,catalog=protected-user-mode", "86.08.0C.00.1A",
      0x10DEu, 0x1D01u, 0x1043u, 0x85F4u, 0xA1u,
      2048u, 1228000u, 1468000u, 3004000u, 64u, 48100u, 8u, 6u,
      384u, 3u, 16u, 24u, 0x130u, 8u, 0x11u, 4u },
    { "gt1030_msi_2gb", "NVIDIA GeForce GT 1030", "MSI", "LP OCV1", "GDDR5", "Micron", "Micron", "B:system-pci=host-mdev,catalog=protected-user-mode", "86.08.0C.00.18",
      0x10DEu, 0x1D01u, 0x1462u, 0x8C98u, 0xA1u,
      2048u, 1266000u, 1519000u, 3004000u, 64u, 48100u, 8u, 10u,
      384u, 3u, 16u, 24u, 0x130u, 8u, 0x11u, 4u },
    { "gtx1050_colorful_2gb", "NVIDIA GeForce GTX 1050", "Colorful", "GTX1050 Gaming 2G V5", "GDDR5", "Samsung", "Samsung", "B:system-pci=host-mdev,catalog=protected-user-mode", "86.07.39.80.02",
      0x10DEu, 0x1C81u, 0x7377u, 0x0000u, 0xA1u,
      2048u, 1354000u, 1455000u, 3504000u, 128u, 112000u, 8u, 1u,
      640u, 5u, 32u, 40u, 0x130u, 7u, 0x11u, 16u },
    { "gtx1050_msi_2gb", "NVIDIA GeForce GTX 1050", "MSI", "Gaming X", "GDDR5", "Micron", "Micron", "B:system-pci=host-mdev,catalog=protected-user-mode", "86.07.39.00.70",
      0x10DEu, 0x1C81u, 0x1462u, 0x3354u, 0xA1u,
      2048u, 1418000u, 1531000u, 3504000u, 128u, 112000u, 8u, 10u,
      640u, 5u, 32u, 40u, 0x130u, 7u, 0x11u, 16u },
    { "gtx1050_gigabyte_2gb", "NVIDIA GeForce GTX 1050", "Gigabyte", "OC", "GDDR5", "SK hynix", "Hynix", "B:system-pci=host-mdev,catalog=protected-user-mode", "86.07.39.00.72",
      0x10DEu, 0x1C81u, 0x1458u, 0x372Du, 0xA1u,
      2048u, 1380000u, 1493000u, 3504000u, 128u, 112000u, 8u, 6u,
      640u, 5u, 32u, 40u, 0x130u, 7u, 0x11u, 16u },
};

#define QEMU_VGPU_PROFILE_CONTRACT_COUNT \
    (sizeof(qemu_vgpu_profile_contracts) / \
     sizeof(qemu_vgpu_profile_contracts[0]))

#endif
