/* Generated by generate-profile-catalog.sh.  Do not edit by hand. */
#ifndef QEMU_VGPU_PROFILE_CATALOG_H
#define QEMU_VGPU_PROFILE_CATALOG_H

#include <stddef.h>
#include <stdint.h>

typedef struct {
    const char *key;
    const char *name;
    const char *board_brand;
    const char *board_model;
    const char *memory_type_name;
    const char *memory_maker_name;
    const char *memory_maker_nvapi_name;
    const char *identity_scope;
    const char *vbios_version;
    uint32_t pci_vendor_id;
    uint32_t pci_device_id;
    uint32_t pci_subvendor_id;
    uint32_t pci_subdevice_id;
    uint32_t pci_revision_id;
    uint32_t vram_mb;
    uint32_t core_clock_khz;
    uint32_t boost_clock_khz;
    uint32_t memory_raw_clock_khz;
    uint32_t memory_bus_bits;
    uint32_t memory_bandwidth_mbps;
    uint32_t memory_type;
    uint32_t memory_maker;
    uint32_t cuda_cores;
    uint32_t shader_subpipes;
    uint32_t rop_count;
    uint32_t tmu_count;
    uint32_t architecture;
    uint32_t implementation;
    uint32_t chip_revision;
    uint32_t pcie_width;
    uint32_t ray_tracing_cores;
    uint32_t tensor_cores;
} QemuVgpuProfileContract;

#define QEMU_VGPU_PROFILE_CATALOG_SCHEMA 2u
#define QEMU_VGPU_PROFILE_CATALOG_SHA256 "FEEA5430609C81C495617607A3500F7A7BEA6CB6AFB4A5156F1918A1ACDCED7B"

static const QemuVgpuProfileContract qemu_vgpu_profile_contracts[] = {
    { "gtx750ti_2gb", "NVIDIA GeForce GTX 750 Ti", "NVIDIA", "Reference", "GDDR5", "Samsung", "Samsung", "B:system-pci=host-mdev,catalog=protected-user-mode", "82.07.41.00.32",
      0x10DEu, 0x1380u, 0x10DEu, 0x1380u, 0xA2u,
      2048u, 1020000u, 1085000u, 2700000u, 128u, 86400u, 8u, 1u,
      640u, 5u, 16u, 40u, 0x110u, 7u, 0x12u, 16u, 0u, 0u },
    { "gt1030_2gb", "NVIDIA GeForce GT 1030", "ASUS", "OEM 85F9", "GDDR5", "Samsung", "Samsung", "B:system-pci=host-mdev,catalog=protected-user-mode", "86.08.46.00.81",
      0x10DEu, 0x1D01u, 0x1043u, 0x85F9u, 0xA1u,
      2048u, 1227000u, 1468000u, 3004000u, 64u, 48100u, 8u, 1u,
      384u, 3u, 16u, 24u, 0x130u, 8u, 0x11u, 4u, 0u, 0u },
    { "gtx1050_2gb", "NVIDIA GeForce GTX 1050", "Dell", "OEM", "GDDR5", "Samsung", "Samsung", "B:system-pci=host-mdev,catalog=protected-user-mode", "86.07.39.40.F4",
      0x10DEu, 0x1C81u, 0x1028u, 0x11C0u, 0xA1u,
      2048u, 1354000u, 1455000u, 3504000u, 128u, 112000u, 8u, 1u,
      640u, 5u, 32u, 40u, 0x130u, 7u, 0x11u, 16u, 0u, 0u },
    { "gt740_1gb", "NVIDIA GeForce GT 740", "MSI", "N740-1GD5", "GDDR5", "Samsung", "Samsung", "B:system-pci=host-mdev,catalog=protected-user-mode", "80.07.D9.00.52",
      0x10DEu, 0x0FC8u, 0x1462u, 0x8A9Eu, 0xA1u,
      1024u, 1006000u, 1006000u, 2500000u, 128u, 80000u, 8u, 1u,
      384u, 4u, 16u, 32u, 0x100u, 7u, 0x11u, 16u, 0u, 0u },
    { "gt740_asus_1gb", "NVIDIA GeForce GT 740", "ASUS", "GT740-OC-1GD5", "GDDR5", "SK hynix", "Hynix", "B:system-pci=host-mdev,catalog=protected-user-mode", "80.07.D9.00.14",
      0x10DEu, 0x0FC8u, 0x1043u, 0x8694u, 0xA1u,
      1024u, 1033000u, 1033000u, 2500000u, 128u, 80000u, 8u, 6u,
      384u, 4u, 16u, 32u, 0x100u, 7u, 0x11u, 16u, 0u, 0u },
    { "gt740_gigabyte_1gb", "NVIDIA GeForce GT 740", "Gigabyte", "GV-N740D5OC-1GI", "GDDR5", "Samsung", "Samsung", "B:system-pci=host-mdev,catalog=protected-user-mode", "80.07.D9.00.2A",
      0x10DEu, 0x0FC8u, 0x1458u, 0x368Du, 0xA1u,
      1024u, 1072000u, 1072000u, 2500000u, 128u, 80000u, 8u, 1u,
      384u, 4u, 16u, 32u, 0x100u, 7u, 0x11u, 16u, 0u, 0u },
    { "gt740_zotac_1gb", "NVIDIA GeForce GT 740", "ZOTAC", "ZT-71002-10L", "GDDR5", "Micron", "Micron", "B:system-pci=host-mdev,catalog=protected-user-mode", "80.07.D9.00.3A",
      0x10DEu, 0x0FC8u, 0x19DAu, 0x4291u, 0xA1u,
      1024u, 993000u, 993000u, 2500000u, 128u, 80000u, 8u, 10u,
      384u, 4u, 16u, 32u, 0x100u, 7u, 0x11u, 16u, 0u, 0u },
    { "gt730_1gb", "NVIDIA GeForce GT 730", "ASUS", "GT730-1GD5-BRK", "GDDR5", "Samsung", "Samsung", "B:system-pci=host-mdev,catalog=protected-user-mode", "80.28.6A.00.0B",
      0x10DEu, 0x1287u, 0x1043u, 0x84E4u, 0xA1u,
      1024u, 902000u, 902000u, 2506000u, 64u, 40100u, 8u, 1u,
      384u, 2u, 8u, 16u, 0x100u, 8u, 0x11u, 8u, 0u, 0u },
    { "gt730_msi_1gb", "NVIDIA GeForce GT 730", "MSI", "N730K-1GD5LP-OC", "GDDR5", "SK hynix", "Hynix", "B:system-pci=host-mdev,catalog=protected-user-mode", "80.28.78.00.48",
      0x10DEu, 0x1287u, 0x1462u, 0x8A9Fu, 0xA1u,
      1024u, 1006000u, 1006000u, 2500000u, 64u, 40000u, 8u, 6u,
      384u, 2u, 8u, 16u, 0x100u, 8u, 0x11u, 8u, 0u, 0u },
    { "gt730_gigabyte_1gb", "NVIDIA GeForce GT 730", "Gigabyte", "GV-N730D5OC-1GI", "GDDR5", "Samsung", "Samsung", "B:system-pci=host-mdev,catalog=protected-user-mode", "80.28.7A.00.26",
      0x10DEu, 0x1287u, 0x1458u, 0x3693u, 0xA1u,
      1024u, 1006000u, 1006000u, 2506000u, 64u, 40100u, 8u, 1u,
      384u, 2u, 8u, 16u, 0x100u, 8u, 0x11u, 8u, 0u, 0u },
    { "gt730_zotac_1gb", "NVIDIA GeForce GT 730", "ZOTAC", "ZT-71102-10L", "GDDR5", "SK hynix", "Hynix", "B:system-pci=host-mdev,catalog=protected-user-mode", "80.28.7A.00.16",
      0x10DEu, 0x1287u, 0x19DAu, 0x730Bu, 0xA1u,
      1024u, 902000u, 902000u, 2506000u, 64u, 40100u, 8u, 6u,
      384u, 2u, 8u, 16u, 0x100u, 8u, 0x11u, 8u, 0u, 0u },
    { "gtx750_asus_1gb", "NVIDIA GeForce GTX 750", "ASUS", "GTX750-PHOC-1GD5", "GDDR5", "Samsung", "Samsung", "B:system-pci=host-mdev,catalog=protected-user-mode", "82.07.25.00.09",
      0x10DEu, 0x1381u, 0x1043u, 0x8644u, 0xA2u,
      1024u, 1059000u, 1137000u, 2700000u, 128u, 86400u, 8u, 1u,
      512u, 4u, 16u, 32u, 0x110u, 7u, 0x12u, 16u, 0u, 0u },
    { "gtx750_msi_1gb", "NVIDIA GeForce GTX 750", "MSI", "N750-GAMING-1GD5-OC", "GDDR5", "SK hynix", "Hynix", "B:system-pci=host-mdev,catalog=protected-user-mode", "82.07.25.00.36",
      0x10DEu, 0x1381u, 0x1462u, 0x3107u, 0xA2u,
      1024u, 1085000u, 1163000u, 2506000u, 128u, 80200u, 8u, 6u,
      512u, 4u, 16u, 32u, 0x110u, 7u, 0x12u, 16u, 0u, 0u },
    { "gtx750_gigabyte_1gb", "NVIDIA GeForce GTX 750", "Gigabyte", "GV-N750OC-1GI", "GDDR5", "Elpida", "Elpida", "B:system-pci=host-mdev,catalog=protected-user-mode", "82.07.32.40.6D",
      0x10DEu, 0x1381u, 0x1458u, 0x362Eu, 0xA2u,
      1024u, 1059000u, 1137000u, 2500000u, 128u, 80000u, 8u, 3u,
      512u, 4u, 16u, 32u, 0x110u, 7u, 0x12u, 16u, 0u, 0u },
    { "gtx750_zotac_1gb", "NVIDIA GeForce GTX 750", "ZOTAC", "ZT-70701-10M", "GDDR5", "Samsung", "Samsung", "B:system-pci=host-mdev,catalog=protected-user-mode", "82.07.32.00.2F",
      0x10DEu, 0x1381u, 0x19DAu, 0x288Bu, 0xA2u,
      1024u, 1033000u, 1111000u, 2506000u, 128u, 80200u, 8u, 1u,
      512u, 4u, 16u, 32u, 0x110u, 7u, 0x12u, 16u, 0u, 0u },
    { "gtx750ti_asus_2gb", "NVIDIA GeForce GTX 750 Ti", "ASUS", "OC", "GDDR5", "Samsung", "Samsung", "B:system-pci=host-mdev,catalog=protected-user-mode", "82.07.32.00.20",
      0x10DEu, 0x1380u, 0x1043u, 0x84BBu, 0xA2u,
      2048u, 1072000u, 1150000u, 2700000u, 128u, 86400u, 8u, 1u,
      640u, 5u, 16u, 40u, 0x110u, 7u, 0x12u, 16u, 0u, 0u },
    { "gtx750ti_msi_2gb", "NVIDIA GeForce GTX 750 Ti", "MSI", "OC", "GDDR5", "SK hynix", "Hynix", "B:system-pci=host-mdev,catalog=protected-user-mode", "82.07.25.00.1F",
      0x10DEu, 0x1380u, 0x1462u, 0x8A9Bu, 0xA2u,
      2048u, 1059000u, 1137000u, 2700000u, 128u, 86400u, 8u, 6u,
      640u, 5u, 16u, 40u, 0x110u, 7u, 0x12u, 16u, 0u, 0u },
    { "gtx750ti_gigabyte_2gb", "NVIDIA GeForce GTX 750 Ti", "Gigabyte", "OC", "GDDR5", "Micron", "Micron", "B:system-pci=host-mdev,catalog=protected-user-mode", "82.07.55.00.05",
      0x10DEu, 0x1380u, 0x1458u, 0x362Du, 0xA2u,
      2048u, 1033000u, 1111000u, 2700000u, 128u, 86400u, 8u, 10u,
      640u, 5u, 16u, 40u, 0x110u, 7u, 0x12u, 16u, 0u, 0u },
    { "gt1030_galax_2gb", "NVIDIA GeForce GT 1030", "GALAX", "EXOC White", "GDDR5", "Samsung", "Samsung", "B:system-pci=host-mdev,catalog=protected-user-mode", "86.08.0C.00.2B",
      0x10DEu, 0x1D01u, 0x10DEu, 0x11C7u, 0xA1u,
      2048u, 1253000u, 1506000u, 3004000u, 64u, 48100u, 8u, 1u,
      384u, 3u, 16u, 24u, 0x130u, 8u, 0x11u, 4u, 0u, 0u },
    { "gt1030_asus_2gb", "NVIDIA GeForce GT 1030", "ASUS", "Silent", "GDDR5", "SK hynix", "Hynix", "B:system-pci=host-mdev,catalog=protected-user-mode", "86.08.0C.00.1A",
      0x10DEu, 0x1D01u, 0x1043u, 0x85F4u, 0xA1u,
      2048u, 1228000u, 1468000u, 3004000u, 64u, 48100u, 8u, 6u,
      384u, 3u, 16u, 24u, 0x130u, 8u, 0x11u, 4u, 0u, 0u },
    { "gt1030_msi_2gb", "NVIDIA GeForce GT 1030", "MSI", "LP OCV1", "GDDR5", "Micron", "Micron", "B:system-pci=host-mdev,catalog=protected-user-mode", "86.08.0C.00.18",
      0x10DEu, 0x1D01u, 0x1462u, 0x8C98u, 0xA1u,
      2048u, 1266000u, 1519000u, 3004000u, 64u, 48100u, 8u, 10u,
      384u, 3u, 16u, 24u, 0x130u, 8u, 0x11u, 4u, 0u, 0u },
    { "gtx1050_colorful_2gb", "NVIDIA GeForce GTX 1050", "Colorful", "GTX1050 Gaming 2G V5", "GDDR5", "Samsung", "Samsung", "B:system-pci=host-mdev,catalog=protected-user-mode", "86.07.39.80.02",
      0x10DEu, 0x1C81u, 0x7377u, 0x0000u, 0xA1u,
      2048u, 1354000u, 1455000u, 3504000u, 128u, 112000u, 8u, 1u,
      640u, 5u, 32u, 40u, 0x130u, 7u, 0x11u, 16u, 0u, 0u },
    { "gtx1050_msi_2gb", "NVIDIA GeForce GTX 1050", "MSI", "Gaming X", "GDDR5", "Micron", "Micron", "B:system-pci=host-mdev,catalog=protected-user-mode", "86.07.39.00.70",
      0x10DEu, 0x1C81u, 0x1462u, 0x3354u, 0xA1u,
      2048u, 1418000u, 1531000u, 3504000u, 128u, 112000u, 8u, 10u,
      640u, 5u, 32u, 40u, 0x130u, 7u, 0x11u, 16u, 0u, 0u },
    { "gtx1050_gigabyte_2gb", "NVIDIA GeForce GTX 1050", "Gigabyte", "OC", "GDDR5", "SK hynix", "Hynix", "B:system-pci=host-mdev,catalog=protected-user-mode", "86.07.39.00.72",
      0x10DEu, 0x1C81u, 0x1458u, 0x372Du, 0xA1u,
      2048u, 1380000u, 1493000u, 3504000u, 128u, 112000u, 8u, 6u,
      640u, 5u, 32u, 40u, 0x130u, 7u, 0x11u, 16u, 0u, 0u },
    { "gtx750ti_evga_sc_2gb", "NVIDIA GeForce GTX 750 Ti", "EVGA", "02G-P4-3753-KR", "GDDR5", "Samsung", "Samsung", "B:system-pci=host-mdev,catalog=protected-user-mode", "82.07.25.00.50",
      0x10DEu, 0x1380u, 0x3842u, 0x3753u, 0xA2u,
      2048u, 1176000u, 1255000u, 2700000u, 128u, 86400u, 8u, 1u,
      640u, 5u, 16u, 40u, 0x110u, 7u, 0x12u, 16u, 0u, 0u },
};

#define QEMU_VGPU_PROFILE_CONTRACT_COUNT \
    (sizeof(qemu_vgpu_profile_contracts) / \
     sizeof(qemu_vgpu_profile_contracts[0]))

#endif
