#ifndef VMATE_IDENTITY_CONFIG_H
#define VMATE_IDENTITY_CONFIG_H

#include <Uefi.h>

#define VMATE_IDENTITY_VALUE_SIZE 65
#define VMATE_IDENTITY_CONFIG_PATH L"\\EFI\\VMate\\identity.ini"

typedef struct {
  CHAR8 BiosVendor[VMATE_IDENTITY_VALUE_SIZE];
  CHAR8 BiosVersion[VMATE_IDENTITY_VALUE_SIZE];
  CHAR8 BiosDate[VMATE_IDENTITY_VALUE_SIZE];
  CHAR8 SystemManufacturer[VMATE_IDENTITY_VALUE_SIZE];
  CHAR8 SystemProduct[VMATE_IDENTITY_VALUE_SIZE];
  CHAR8 SystemVersion[VMATE_IDENTITY_VALUE_SIZE];
  CHAR8 SystemSerial[VMATE_IDENTITY_VALUE_SIZE];
  CHAR8 SystemSku[VMATE_IDENTITY_VALUE_SIZE];
  CHAR8 SystemFamily[VMATE_IDENTITY_VALUE_SIZE];
  CHAR8 BoardManufacturer[VMATE_IDENTITY_VALUE_SIZE];
  CHAR8 BoardProduct[VMATE_IDENTITY_VALUE_SIZE];
  CHAR8 BoardVersion[VMATE_IDENTITY_VALUE_SIZE];
  CHAR8 BoardSerial[VMATE_IDENTITY_VALUE_SIZE];
  CHAR8 BoardAsset[VMATE_IDENTITY_VALUE_SIZE];
  CHAR8 ChassisManufacturer[VMATE_IDENTITY_VALUE_SIZE];
  CHAR8 ChassisVersion[VMATE_IDENTITY_VALUE_SIZE];
  CHAR8 ChassisSerial[VMATE_IDENTITY_VALUE_SIZE];
  CHAR8 ChassisAsset[VMATE_IDENTITY_VALUE_SIZE];
  CHAR8 CpuManufacturer[VMATE_IDENTITY_VALUE_SIZE];
  CHAR8 CpuVersion[VMATE_IDENTITY_VALUE_SIZE];
  CHAR8 CpuSerial[VMATE_IDENTITY_VALUE_SIZE];
  CHAR8 CpuAsset[VMATE_IDENTITY_VALUE_SIZE];
  CHAR8 CpuPart[VMATE_IDENTITY_VALUE_SIZE];
  CHAR8 MemoryManufacturer[VMATE_IDENTITY_VALUE_SIZE];
  CHAR8 MemorySerial[VMATE_IDENTITY_VALUE_SIZE];
  CHAR8 MemoryAsset[VMATE_IDENTITY_VALUE_SIZE];
  CHAR8 MemoryPart[VMATE_IDENTITY_VALUE_SIZE];
  UINT8 ChassisType;
  UINT8 MemoryType;
  UINT16 MemorySpeed;
  UINT16 MemoryConfiguredSpeed;
} VMATE_IDENTITY_CONFIG;

EFI_STATUS
VMateLoadIdentityConfig (
  IN EFI_HANDLE ImageHandle,
  OUT VMATE_IDENTITY_CONFIG *Config,
  OUT UINTN *ParsedFields
  );

#endif
